language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI server's home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/hnu-pioneer.zip

deploy:
  - provider: s3
    access_ky_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: hnu-pioneer-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    access_key_key: $AWS_SECRET_KEY

    bucket: hnu-pioneer-build
    key: hnu-pioneer.zip
    bundle_type: zip
    appication: hnu-pioneer
    deployment_group: hnu-pioneer-group
    region: ap-northeast-2
    wait-until-deployed: true

# Alarm after complete CI
notifications:
  email:
    recipients:
      - dbfpzk142@gmail.com
